### ISSUE TITLE
Updated offsets but now it says 'expected expression next to dwLocalPlayer'

### ISSUE THREAD

**Issue by LionHackerman** [HeathHowren/CSGO-ImGui-DX9-Kiero-Hook#1]
![image](https://user-images.githubusercontent.com/58070003/85190819-6048a680-b2ff-11ea-9a80-fd28b08a668a.png)

![image](https://user-images.githubusercontent.com/58070003/85190825-7191b300-b2ff-11ea-9893-83aa63487a4d.png)

**Comment by HeathHowren** [comment]
The error with dwLocalPlayer comes from not defining it. Include the offsets.h file, or put #define dwLocalPlayer XXXXXXX in the main.
