### ISSUE TITLE
When I inject in-lobby then press 'INS' game crashes

### ISSUE THREAD

**Issue by LionHackerman** [HeathHowren/CSGO-ImGui-DX9-Kiero-Hook#2]
As the title says however if I inject in lobby then get into a game, I can press 'INS' and it dosen't crash. Something to do with a gamemode check or something?

**Comment by HeathHowren** [comment]
Add null pointer checks in the code.

**Comment by Bombonels** [comment]
Just Delete This:
#define m_iDefaultFOV 0x332C
From The Main Folder Is At The Start
